replicaCount: 1
image:
  repository: supinfo4kube/api-gateway
  tag: 1.0.1
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
env:
  SPRING_PROFILES_ACTIVE: production-microservice
resources: {}
