apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-position-tracker
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: position-tracker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "{{ .Values.env.SPRING_PROFILES_ACTIVE }}"
