apiVersion: v1
kind: Service
metadata:
  name: fleetman1-queue
  namespace: fleetman1
spec:
  selector:
    app: fleetman1-queue
  ports:
    - protocol: TCP
      port: 5672        # Port exposé pour RabbitMQ
      targetPort: 5672  # Port dans le conteneur
  type: ClusterIP
