replicaCount: 1
image:
  repository: mongo
  tag: 3.6.23
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 27017
persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce
resources: {}
